# Generated by Django 4.1.5 on 2023-01-04 23:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64, verbose_name='username')),
                ('firstname', models.CharField(max_length=64, verbose_name='first_name')),
                ('lastname', models.CharField(max_length=64, verbose_name='last_name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='last_name')),
                ('birthday', models.DateField()),
            ],
        ),
    ]
