# Generated by Django 4.1.5 on 2023-01-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.BooleanField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1),
        ),
    ]
